"""
SQLAlchemy ORM Models for Health Assistant
"""

from sqlalchemy import Column, String, DateTime, Text, Integer, Float, Boolean, JSON, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime, timedelta
import uuid

Base = declarative_base()

class User(Base):
    """User account with Google Health & Telegram integration"""
    __tablename__ = "users"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    telegram_chat_id = Column(String, unique=True, nullable=False, index=True)
    google_user_id = Column(String, unique=True, nullable=False, index=True)
    email = Column(String, unique=True, nullable=False, index=True)
    first_name = Column(String, nullable=True)
    last_name = Column(String, nullable=True)

    # Status
    is_active = Column(Boolean, default=True)
    connected = Column(Boolean, default=False)

    # User preferences
    summary_hour = Column(Integer, default=7)  # 7 AM for daily summary
    summary_minute = Column(Integer, default=0)
    timezone = Column(String, default="UTC")

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    last_summary_sent = Column(DateTime, nullable=True)

    # Relationships
    oauth_tokens = relationship("OAuthToken", back_populates="user", cascade="all, delete-orphan")
    health_summaries = relationship("HealthSummary", back_populates="user", cascade="all, delete-orphan")


class OAuthToken(Base):
    """Google OAuth tokens - securely stored"""
    __tablename__ = "oauth_tokens"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)

    # Tokens
    access_token = Column(Text, nullable=False)
    refresh_token = Column(Text, nullable=True)

    # Expiration of the *access* token (about an hour).
    expires_at = Column(DateTime, nullable=False)
    scope = Column(String)

    # When the current refresh token was issued by a full consent flow.
    # Google doesn't tell us when a refresh token expires, and while the
    # OAuth consent screen is in Testing it silently stops working after 7
    # days — so this is the only basis for warning a user *before* their
    # summaries stop arriving. Set on exchange_code, not on refresh: a
    # refresh returns a new access token but does not restart the 7-day
    # clock on the refresh token.
    refresh_token_issued_at = Column(DateTime, nullable=True)

    # When we last told this user their connection needs reconnecting, so
    # the daily run nags once rather than every morning. Cleared on
    # reconnect (the whole row is replaced).
    reconnect_notified_at = Column(DateTime, nullable=True)

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    user = relationship("User", back_populates="oauth_tokens")

    @property
    def is_expired(self):
        return datetime.utcnow() > self.expires_at

    @property
    def is_expiring_soon(self):
        # Refresh if expiring in next 5 minutes
        return datetime.utcnow() > (self.expires_at - timedelta(minutes=5))


class HealthSummary(Base):
    """Daily health summaries generated by Claude"""
    __tablename__ = "health_summaries"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)

    # Raw Fitbit data
    raw_fitbit_data = Column(JSON, nullable=False)

    # Summary content
    summary = Column(Text, nullable=False)  # Claude-generated markdown

    # Metrics snapshot
    sleep_duration_minutes = Column(Integer, nullable=True)
    sleep_efficiency = Column(Float, nullable=True)
    steps_count = Column(Integer, nullable=True)
    active_zone_minutes = Column(Integer, nullable=True)
    calories_burned = Column(Integer, nullable=True)
    resting_heart_rate = Column(Integer, nullable=True)

    # Metadata
    summary_date = Column(DateTime, default=datetime.utcnow, index=True)
    sent_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    user = relationship("User", back_populates="health_summaries")


class InteractionLog(Base):
    """Log user interactions for debugging and analytics"""
    __tablename__ = "interaction_logs"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, nullable=False, index=True)

    # Interaction details
    interaction_type = Column(String, nullable=False)  # "summary", "query", "error", etc.
    user_message = Column(Text, nullable=True)
    claude_response = Column(Text, nullable=True)

    # Tool calling info
    mcp_tools_called = Column(JSON, nullable=True)  # List of tools used

    # Status
    success = Column(Boolean, default=True)
    error_message = Column(Text, nullable=True)

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
