"""Rename interaction_logs.claude_response to assistant_response

Left over from before the project moved from Claude to Gemini. The column is
provider-neutral now, so the name is too.

Written by hand rather than autogenerated. `--autogenerate` cannot recognise
a rename — it sees a dropped column and an added one, and emits DROP + ADD,
which discards whatever the column held. `alter_column(new_column_name=...)`
renames in place and keeps the data. The table happens to be empty today
(nothing writes InteractionLog yet), so both would have worked here, but the
drop+create version would be a live data-loss bug the moment that changes.

Revision ID: 0d57cf1a459e
Revises: 5fa6ffca0dce
Create Date: 2026-08-30 18:03:05.029415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d57cf1a459e'
down_revision: Union[str, None] = '5fa6ffca0dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "interaction_logs",
        "claude_response",
        new_column_name="assistant_response",
        existing_type=sa.Text(),
        existing_nullable=True,
    )


def downgrade() -> None:
    op.alter_column(
        "interaction_logs",
        "assistant_response",
        new_column_name="claude_response",
        existing_type=sa.Text(),
        existing_nullable=True,
    )
