"""Add refresh_token_issued_at and reconnect_notified_at to oauth_tokens

Revision ID: 5fa6ffca0dce
Revises: e15676c1e091
Create Date: 2026-08-25 00:26:41.301042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa6ffca0dce'
down_revision: Union[str, None] = 'e15676c1e091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_tokens', sa.Column('refresh_token_issued_at', sa.DateTime(), nullable=True))
    op.add_column('oauth_tokens', sa.Column('reconnect_notified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_tokens', 'reconnect_notified_at')
    op.drop_column('oauth_tokens', 'refresh_token_issued_at')
    # ### end Alembic commands ###
