"""Baseline schema: users, oauth_tokens, health_summaries, interaction_logs

Captures the schema exactly as `Base.metadata.create_all()` had been
building it, so this is a no-op against any database that was already
initialised the old way.

**If you have an existing database** (a Neon instance created before
migrations existed), do NOT run `alembic upgrade head` against it — the
CREATE TABLEs will fail on tables that already exist. Run this instead, once:

    alembic stamp head

which records "this database is already at this revision" without executing
anything. Fresh databases get `alembic upgrade head` as normal.

Revision ID: e15676c1e091
Revises:
Create Date: 2026-08-24 21:40:19.327538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15676c1e091'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('claude_response', sa.Text(), nullable=True),
    sa.Column('mcp_tools_called', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_logs_created_at'), 'interaction_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_interaction_logs_user_id'), 'interaction_logs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(), nullable=False),
    sa.Column('google_user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=True),
    sa.Column('summary_hour', sa.Integer(), nullable=True),
    sa.Column('summary_minute', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_summary_sent', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_user_id'), 'users', ['google_user_id'], unique=True)
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=True)
    op.create_table('health_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('raw_fitbit_data', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sleep_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_efficiency', sa.Float(), nullable=True),
    sa.Column('steps_count', sa.Integer(), nullable=True),
    sa.Column('active_zone_minutes', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('summary_date', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_summaries_summary_date'), 'health_summaries', ['summary_date'], unique=False)
    op.create_index(op.f('ix_health_summaries_user_id'), 'health_summaries', ['user_id'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_tokens_user_id'), 'oauth_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_tokens_user_id'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_health_summaries_user_id'), table_name='health_summaries')
    op.drop_index(op.f('ix_health_summaries_summary_date'), table_name='health_summaries')
    op.drop_table('health_summaries')
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_interaction_logs_user_id'), table_name='interaction_logs')
    op.drop_index(op.f('ix_interaction_logs_created_at'), table_name='interaction_logs')
    op.drop_table('interaction_logs')
    # ### end Alembic commands ###
